#!/bin/sh

#
# Copyright © 2015-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced functionality shells are not supported.
#
#   (2) If you have a 64-bit JVM, you need to have a 64-bit C library installed
#       on your system. If you have a 32-bit JVM, you need to have a 32-bit C
#       library installed on your system. If you have both 32-bit and 64-bit
#       JVMs and C libraries installed, you need to ensure that the JVM
#       and C library have the same bitness (32 or 64).
#
#       On Linux, you can check the bitness of your JVM with:
#
#           java -d64 -version
#
#       If this command succeeds, you have a 64-bit JVM. If it fails, you have
#       a 32-bit JVM.
#
#       On Linux, you can check the bitness of your C library with:
#
#           ldd /bin/ls | grep -E 'libc.so|libc-.*\.so'
#
#       If this prints a path ending with "x86_64" or "64", you have a 64-bit
#       C library. If this prints a path ending with "i386" or "i686", you have
#       a 32-bit C library.
#
#   (3) If you have a 64-bit JVM and a 32-bit C library, or vice versa, you need
#       to install a JVM and C library with the same bitness. On a 64-bit
#       system, it is recommended to install a 64-bit JVM and a 64-bit C
#       library.
#
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing / for empty string.
    [ -h "$app_path" ]
do
    app_path=$APP_HOME
    # if it's a relative symlink, prepend the dir of the symlink's path
    case $app_path in             
    /*)   ;;                       
    *)    app_path=$(cd "$(dirname -- "$app_path")" && pwd -P)/"${app_path##*/}" ;; 
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" > /dev/null && pwd -P || echo "${APP_HOME:-./}")

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname -s)" in                
  CYGWIN* )         cygwin=true  ;; 
  Darwin* )         darwin=true  ;; 
  MSYS* | MINGW* )  msys=true    ;; 
  NonStop* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD=$JAVA_HOME/bin/java
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation or add the Java executable to your PATH."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$(ulimit -H -n) ||
            warn "Could not query maximum file descriptor limit"
      ;;
    esac
    case $MAX_FD in  
      '' | soft) :;;           # Use current ulimit
      *)                      
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
      ;;
    esac
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"

exec "$JAVACMD" "$@"
